# Generated by Django 2.1.3 on 2019-01-10 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiniBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='微博正文')),
                ('image', models.ImageField(blank=True, max_length=200, null=True, upload_to='blogImage/%Y/%m', verbose_name='图片')),
                ('click_num', models.IntegerField(blank=True, default=0, null=True, verbose_name='微博点击数')),
                ('good_num', models.IntegerField(blank=True, default=0, null=True, verbose_name='点赞数')),
                ('comment_num', models.IntegerField(blank=True, default=0, null=True, verbose_name='评论数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发布时间')),
                ('need_unfold', models.IntegerField(choices=[(0, '不需展开'), (1, '需要展开且未展开'), (2, '需展开且已展开')], default=0)),
            ],
            options={
                'verbose_name': '微博',
                'verbose_name_plural': '微博',
            },
        ),
    ]
