# Generated by Django 2.1.3 on 2019-01-10 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('miniblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='miniblog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='miniblog_set', to=settings.AUTH_USER_MODEL, verbose_name='发布用戶'),
        ),
    ]
