# Generated by Django 2.1.3 on 2019-01-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniblog', '0002_miniblog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='miniblog',
            name='collect_num',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='收藏数'),
        ),
    ]
