# Generated by Django 2.1.3 on 2019-01-10 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miniblog', '0003_miniblog_collect_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topicname', models.CharField(default='', max_length=50, verbose_name='话题名称')),
            ],
        ),
        migrations.AddField(
            model_name='miniblog',
            name='related_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='miniblog.Topic', verbose_name='微博相关话题'),
        ),
    ]
