# Generated by Django 2.1.3 on 2019-01-10 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniblog', '0004_auto_20190110_2349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': '微博话题', 'verbose_name_plural': '微博话题'},
        ),
    ]
