# Generated by Django 2.1.3 on 2019-01-10 23:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniblog', '0005_auto_20190110_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间'),
        ),
    ]
