# Generated by Django 2.1.3 on 2019-01-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniblog', '0006_topic_add_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='miniblog',
            name='has_pic',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='是否有图'),
        ),
    ]
