# Generated by Django 2.1.3 on 2019-01-10 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_auto_20190110_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfav',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='usergood',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='usermessage',
            name='user',
        ),
    ]
