# Generated by Django 2.1.3 on 2019-01-10 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miniblog', '0002_miniblog_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0004_auto_20190110_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfav',
            name='blogid',
        ),
        migrations.RemoveField(
            model_name='usergood',
            name='blogid',
        ),
        migrations.RemoveField(
            model_name='usermessage',
            name='userid',
        ),
        migrations.AddField(
            model_name='userfav',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='miniblog.MiniBlog', verbose_name='被收藏微博'),
        ),
        migrations.AddField(
            model_name='usergood',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='miniblog.MiniBlog', verbose_name='被点赞微博'),
        ),
        migrations.AddField(
            model_name='usermessage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='接收用户'),
        ),
    ]
