# Generated by Django 2.1.4 on 2019-01-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='blog_id',
            field=models.IntegerField(default=0, verbose_name='微博id'),
        ),
    ]
