# Generated by Django 2.1.4 on 2019-01-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='message_nums',
            field=models.IntegerField(default=0, verbose_name='未读消息数'),
        ),
    ]
